// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductStore.Api.Data;

#nullable disable

namespace ProductStore.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ProductStore.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ProductStore.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CosmosAvgPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosBrandName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosBrandPictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosCommercialDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosGpcCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosGpcDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CosmosGrossWeightGrams")
                        .HasColumnType("REAL");

                    b.Property<string>("CosmosGtin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CosmosHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("CosmosLength")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("CosmosMaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CosmosMinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosNcmCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosNcmDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CosmosNetWeightGrams")
                        .HasColumnType("REAL");

                    b.Property<string>("CosmosPriceLabel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CosmosThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CosmosWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductStore.Api.Models.Product", b =>
                {
                    b.HasOne("ProductStore.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductStore.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
